### Initialize first
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-06-18",
    "capabilities": {
      "roots": {
        "listChanged": true
      },
      "sampling": {},
      "elicitation": {}
    },
    "clientInfo": {
      "name": "ExampleClient",
      "title": "Example Client Display Name",
      "version": "1.0.0"
    }
  }
}

### Try and fail to establish SSE stream
GET http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json


### list available tools
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/list",
    "params": {}
}

### Call the multiply tool:
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "multiply",
    "arguments": {
      "x": 5,
      "y": 10
    }
  }
}

### retrieve name resource
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "resources/read",
  "params": {
    "uri": "names://"
  }
}

### list all prompts
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 5,
  "method": "prompts/list"
}

### retrieve a prompt
POST http://localhost:3000/mcp
Accept: application/json; text/event-stream
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 6,
  "method": "prompts/get",
  "params": {
    "name": "write-a-poem",
    "arguments": {
      "name": "Alex"
    }
  }
}